services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - backend

  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db-data:
